default: &default  
  adapter: mysql2 
  encoding: postgresql
  pool: 5   

development:
  <<: *default
  database: my_conference_dev

production:
  <<: *default
  url: <%= ENV['HEROKU_POSTGRESQL_JADE_URL'] %>
